# ContactPoint type for Person contact details
type ContactPoint implements Thing {
  id: ID!
  name: String!
  alternateName: String
  description: String
  url: String
  image: String
  additionalType: String
  sameAs: String
  identifier: String
  disambiguatingDescription: String

  telephone: String           # Telephone number of the contact point
  email: String               # Email of the contact point
}
